expense/urls.py
from django.urls import path

from . import views

app_name = 'expense'
urlpatterns = [
    path('', views.index, name='index'),
    path('/delete/', views.delete, name='delete'),
]

income_expence/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('expense', include('expense.urls')),
    path('admin/', admin.site.urls),
]

expense/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Expense(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    pub_date = models.DateTimeField('date of paid')

    def __str__(self):
        return self.title

    def was_paid_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

expense/views.py
from django.shortcuts import get_object_or_404, render, redirect

# Create your views here.
from .models import Expense
from .form import ExpenseForm
from django.utils import timezone
from django.views.decorators.http import require_POST


def index(request):
    today = timezone.now()
    expenses = Expense.objects.all()
    total_price = sum(expense.price for expense in expenses)
    form = ExpenseForm(request.POST or None)
    context = {
        'now': today,
        'expenses' : expenses,
        'form': form,
        'total_price': total_price,
    }
    if form.is_valid():
        form.save()
        return redirect('expense:index')
    return render(request, 'expense/index.html', context)

@require_POST
def delete(request):
    delete_ids = request.POST.getlist('delete_ids')
    if delete_ids:
        Expense.objects.filter(id__in=delete_ids).delete()
    return redirect('expense:index')

expense/templates/expense/index.html
{% load static %}
{% load tz %}

<html>
    <head>
        <meta charset="utf-8">
        <title>HousekeepingBook</title>
        <link rel="stylesheet" type="text/css" href="{% static 'expense/style.css' %}">
    </head>
    <body>
        <h1>{% now "Y-m-d" %}</h1>
        <form action="/expense" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <input type="submit" value="送信">
        </form>
        <form method="post" action="{% url 'expense:delete' %}">
        <table>
            <tr>
                <th></th>
                <th>日付</th>
                <th>用途</th>
                <th>金額</th>
            </tr>
            {% if expenses %}
            {% for exp in expenses %}
            <tr>
                <td><input type="checkbox" name="delete_ids" value="{{ exp.id }}"></td>
                <td>{{ exp.pub_date | date:"y/n/j"}}</td>
                <td>{{ exp.title }}</td>
                <td>{{ exp.price }}円</td>
            </tr>
            {% endfor %}
            <tr>
                <td>合計</td>
                <td></td>
                <td></td>
                <td>{{ total_price }}円</td>
            </tr>
            {% csrf_token %}
        {% endif %}
        </table>
        <input type="submit" value="削除">
        </form>
    </body>
</html>